# This is a basic workflow to help you get started with Actions

name: auto_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - develop
      - auto_upgrade_version

  pull_request:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    
    steps:

    
   # Check out source code
    - name: Checkout Source Code
      uses: actions/checkout@v2
    
    # Setup Java 
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        
    # Setup Flutter 
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
    - name: install Melos
      run: dart pub global activate melos

    

    # Setup Build dev     
    - name: Build Dev
      run: |
        cd app/rong_vang_dev
        flutter pub get 
        #flutter build ipa
        flutter build apk
    - name: send build status to telegram
      uses: lienminhquang/telegram_action@v1.3
      if: always()
      with:
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }} # user id or channel name secret
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }} # token secret
        message: ${{ job.status }} # do not modify this line

    
